# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Testing Website for Git from Github.com
email: eric22154@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you are seeing this, that means I can finally edit things on Github! Go use it at github.com!
baseurl: "/testing" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Quantumleap459

# Build settings
markdown: kramdown
